package com.telenav.wzone.database.dto;

import java.math.BigDecimal;
import java.util.Date;

public class CarpoolOffer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.FROM_STOP
     *
     * @mbggenerated
     */
    private String fromStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.FROM_STOP_LAT
     *
     * @mbggenerated
     */
    private BigDecimal fromStopLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.FROM_STOP_LON
     *
     * @mbggenerated
     */
    private BigDecimal fromStopLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.TO_STOP
     *
     * @mbggenerated
     */
    private String toStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.TO_STOP_LAT
     *
     * @mbggenerated
     */
    private BigDecimal toStopLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.TO_STOP_LON
     *
     * @mbggenerated
     */
    private BigDecimal toStopLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.IS_HIDDEN
     *
     * @mbggenerated
     */
    private String isHidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.ID
     *
     * @return the value of ttx_carpool_offer.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.ID
     *
     * @param id the value for ttx_carpool_offer.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.USER_ID
     *
     * @return the value of ttx_carpool_offer.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.USER_ID
     *
     * @param userId the value for ttx_carpool_offer.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.FROM_STOP
     *
     * @return the value of ttx_carpool_offer.FROM_STOP
     *
     * @mbggenerated
     */
    public String getFromStop() {
        return fromStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.FROM_STOP
     *
     * @param fromStop the value for ttx_carpool_offer.FROM_STOP
     *
     * @mbggenerated
     */
    public void setFromStop(String fromStop) {
        this.fromStop = fromStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.FROM_STOP_LAT
     *
     * @return the value of ttx_carpool_offer.FROM_STOP_LAT
     *
     * @mbggenerated
     */
    public BigDecimal getFromStopLat() {
        return fromStopLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.FROM_STOP_LAT
     *
     * @param fromStopLat the value for ttx_carpool_offer.FROM_STOP_LAT
     *
     * @mbggenerated
     */
    public void setFromStopLat(BigDecimal fromStopLat) {
        this.fromStopLat = fromStopLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.FROM_STOP_LON
     *
     * @return the value of ttx_carpool_offer.FROM_STOP_LON
     *
     * @mbggenerated
     */
    public BigDecimal getFromStopLon() {
        return fromStopLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.FROM_STOP_LON
     *
     * @param fromStopLon the value for ttx_carpool_offer.FROM_STOP_LON
     *
     * @mbggenerated
     */
    public void setFromStopLon(BigDecimal fromStopLon) {
        this.fromStopLon = fromStopLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.TO_STOP
     *
     * @return the value of ttx_carpool_offer.TO_STOP
     *
     * @mbggenerated
     */
    public String getToStop() {
        return toStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.TO_STOP
     *
     * @param toStop the value for ttx_carpool_offer.TO_STOP
     *
     * @mbggenerated
     */
    public void setToStop(String toStop) {
        this.toStop = toStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.TO_STOP_LAT
     *
     * @return the value of ttx_carpool_offer.TO_STOP_LAT
     *
     * @mbggenerated
     */
    public BigDecimal getToStopLat() {
        return toStopLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.TO_STOP_LAT
     *
     * @param toStopLat the value for ttx_carpool_offer.TO_STOP_LAT
     *
     * @mbggenerated
     */
    public void setToStopLat(BigDecimal toStopLat) {
        this.toStopLat = toStopLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.TO_STOP_LON
     *
     * @return the value of ttx_carpool_offer.TO_STOP_LON
     *
     * @mbggenerated
     */
    public BigDecimal getToStopLon() {
        return toStopLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.TO_STOP_LON
     *
     * @param toStopLon the value for ttx_carpool_offer.TO_STOP_LON
     *
     * @mbggenerated
     */
    public void setToStopLon(BigDecimal toStopLon) {
        this.toStopLon = toStopLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.STATUS
     *
     * @return the value of ttx_carpool_offer.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.STATUS
     *
     * @param status the value for ttx_carpool_offer.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.IS_HIDDEN
     *
     * @return the value of ttx_carpool_offer.IS_HIDDEN
     *
     * @mbggenerated
     */
    public String getIsHidden() {
        return isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.IS_HIDDEN
     *
     * @param isHidden the value for ttx_carpool_offer.IS_HIDDEN
     *
     * @mbggenerated
     */
    public void setIsHidden(String isHidden) {
        this.isHidden = isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.CREATE_TIME
     *
     * @return the value of ttx_carpool_offer.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.CREATE_TIME
     *
     * @param createTime the value for ttx_carpool_offer.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.UPDATE_TIME
     *
     * @return the value of ttx_carpool_offer.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.UPDATE_TIME
     *
     * @param updateTime the value for ttx_carpool_offer.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}