package com.telenav.wzone.database.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarpoolOfferExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public CarpoolOfferExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFromStopIsNull() {
            addCriterion("FROM_STOP is null");
            return (Criteria) this;
        }

        public Criteria andFromStopIsNotNull() {
            addCriterion("FROM_STOP is not null");
            return (Criteria) this;
        }

        public Criteria andFromStopEqualTo(String value) {
            addCriterion("FROM_STOP =", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopNotEqualTo(String value) {
            addCriterion("FROM_STOP <>", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopGreaterThan(String value) {
            addCriterion("FROM_STOP >", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopGreaterThanOrEqualTo(String value) {
            addCriterion("FROM_STOP >=", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopLessThan(String value) {
            addCriterion("FROM_STOP <", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopLessThanOrEqualTo(String value) {
            addCriterion("FROM_STOP <=", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopLike(String value) {
            addCriterion("FROM_STOP like", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopNotLike(String value) {
            addCriterion("FROM_STOP not like", value, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopIn(List<String> values) {
            addCriterion("FROM_STOP in", values, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopNotIn(List<String> values) {
            addCriterion("FROM_STOP not in", values, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopBetween(String value1, String value2) {
            addCriterion("FROM_STOP between", value1, value2, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopNotBetween(String value1, String value2) {
            addCriterion("FROM_STOP not between", value1, value2, "fromStop");
            return (Criteria) this;
        }

        public Criteria andFromStopLatIsNull() {
            addCriterion("FROM_STOP_LAT is null");
            return (Criteria) this;
        }

        public Criteria andFromStopLatIsNotNull() {
            addCriterion("FROM_STOP_LAT is not null");
            return (Criteria) this;
        }

        public Criteria andFromStopLatEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LAT =", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatNotEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LAT <>", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatGreaterThan(BigDecimal value) {
            addCriterion("FROM_STOP_LAT >", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LAT >=", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatLessThan(BigDecimal value) {
            addCriterion("FROM_STOP_LAT <", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LAT <=", value, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatIn(List<BigDecimal> values) {
            addCriterion("FROM_STOP_LAT in", values, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatNotIn(List<BigDecimal> values) {
            addCriterion("FROM_STOP_LAT not in", values, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROM_STOP_LAT between", value1, value2, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROM_STOP_LAT not between", value1, value2, "fromStopLat");
            return (Criteria) this;
        }

        public Criteria andFromStopLonIsNull() {
            addCriterion("FROM_STOP_LON is null");
            return (Criteria) this;
        }

        public Criteria andFromStopLonIsNotNull() {
            addCriterion("FROM_STOP_LON is not null");
            return (Criteria) this;
        }

        public Criteria andFromStopLonEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LON =", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonNotEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LON <>", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonGreaterThan(BigDecimal value) {
            addCriterion("FROM_STOP_LON >", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LON >=", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonLessThan(BigDecimal value) {
            addCriterion("FROM_STOP_LON <", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FROM_STOP_LON <=", value, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonIn(List<BigDecimal> values) {
            addCriterion("FROM_STOP_LON in", values, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonNotIn(List<BigDecimal> values) {
            addCriterion("FROM_STOP_LON not in", values, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROM_STOP_LON between", value1, value2, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andFromStopLonNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FROM_STOP_LON not between", value1, value2, "fromStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopIsNull() {
            addCriterion("TO_STOP is null");
            return (Criteria) this;
        }

        public Criteria andToStopIsNotNull() {
            addCriterion("TO_STOP is not null");
            return (Criteria) this;
        }

        public Criteria andToStopEqualTo(String value) {
            addCriterion("TO_STOP =", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopNotEqualTo(String value) {
            addCriterion("TO_STOP <>", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopGreaterThan(String value) {
            addCriterion("TO_STOP >", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopGreaterThanOrEqualTo(String value) {
            addCriterion("TO_STOP >=", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopLessThan(String value) {
            addCriterion("TO_STOP <", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopLessThanOrEqualTo(String value) {
            addCriterion("TO_STOP <=", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopLike(String value) {
            addCriterion("TO_STOP like", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopNotLike(String value) {
            addCriterion("TO_STOP not like", value, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopIn(List<String> values) {
            addCriterion("TO_STOP in", values, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopNotIn(List<String> values) {
            addCriterion("TO_STOP not in", values, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopBetween(String value1, String value2) {
            addCriterion("TO_STOP between", value1, value2, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopNotBetween(String value1, String value2) {
            addCriterion("TO_STOP not between", value1, value2, "toStop");
            return (Criteria) this;
        }

        public Criteria andToStopLatIsNull() {
            addCriterion("TO_STOP_LAT is null");
            return (Criteria) this;
        }

        public Criteria andToStopLatIsNotNull() {
            addCriterion("TO_STOP_LAT is not null");
            return (Criteria) this;
        }

        public Criteria andToStopLatEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LAT =", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatNotEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LAT <>", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatGreaterThan(BigDecimal value) {
            addCriterion("TO_STOP_LAT >", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LAT >=", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatLessThan(BigDecimal value) {
            addCriterion("TO_STOP_LAT <", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LAT <=", value, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatIn(List<BigDecimal> values) {
            addCriterion("TO_STOP_LAT in", values, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatNotIn(List<BigDecimal> values) {
            addCriterion("TO_STOP_LAT not in", values, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TO_STOP_LAT between", value1, value2, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TO_STOP_LAT not between", value1, value2, "toStopLat");
            return (Criteria) this;
        }

        public Criteria andToStopLonIsNull() {
            addCriterion("TO_STOP_LON is null");
            return (Criteria) this;
        }

        public Criteria andToStopLonIsNotNull() {
            addCriterion("TO_STOP_LON is not null");
            return (Criteria) this;
        }

        public Criteria andToStopLonEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LON =", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonNotEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LON <>", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonGreaterThan(BigDecimal value) {
            addCriterion("TO_STOP_LON >", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LON >=", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonLessThan(BigDecimal value) {
            addCriterion("TO_STOP_LON <", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TO_STOP_LON <=", value, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonIn(List<BigDecimal> values) {
            addCriterion("TO_STOP_LON in", values, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonNotIn(List<BigDecimal> values) {
            addCriterion("TO_STOP_LON not in", values, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TO_STOP_LON between", value1, value2, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andToStopLonNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TO_STOP_LON not between", value1, value2, "toStopLon");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIsNull() {
            addCriterion("IS_HIDDEN is null");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIsNotNull() {
            addCriterion("IS_HIDDEN is not null");
            return (Criteria) this;
        }

        public Criteria andIsHiddenEqualTo(String value) {
            addCriterion("IS_HIDDEN =", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotEqualTo(String value) {
            addCriterion("IS_HIDDEN <>", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenGreaterThan(String value) {
            addCriterion("IS_HIDDEN >", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenGreaterThanOrEqualTo(String value) {
            addCriterion("IS_HIDDEN >=", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenLessThan(String value) {
            addCriterion("IS_HIDDEN <", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenLessThanOrEqualTo(String value) {
            addCriterion("IS_HIDDEN <=", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenLike(String value) {
            addCriterion("IS_HIDDEN like", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotLike(String value) {
            addCriterion("IS_HIDDEN not like", value, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenIn(List<String> values) {
            addCriterion("IS_HIDDEN in", values, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotIn(List<String> values) {
            addCriterion("IS_HIDDEN not in", values, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenBetween(String value1, String value2) {
            addCriterion("IS_HIDDEN between", value1, value2, "isHidden");
            return (Criteria) this;
        }

        public Criteria andIsHiddenNotBetween(String value1, String value2) {
            addCriterion("IS_HIDDEN not between", value1, value2, "isHidden");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ttx_carpool_offer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}