package com.telenav.wzone.database.dto;

public class CarpoolOfferWithBLOBs extends CarpoolOffer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.VIA_POINTS
     *
     * @mbggenerated
     */
    private String viaPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_carpool_offer.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.VIA_POINTS
     *
     * @return the value of ttx_carpool_offer.VIA_POINTS
     *
     * @mbggenerated
     */
    public String getViaPoints() {
        return viaPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.VIA_POINTS
     *
     * @param viaPoints the value for ttx_carpool_offer.VIA_POINTS
     *
     * @mbggenerated
     */
    public void setViaPoints(String viaPoints) {
        this.viaPoints = viaPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_carpool_offer.DESCRIPTION
     *
     * @return the value of ttx_carpool_offer.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_carpool_offer.DESCRIPTION
     *
     * @param description the value for ttx_carpool_offer.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}