package com.telenav.wzone.database.dto;

import java.util.Date;

public class DriverProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.REAL_NAME
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.PHOTO
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.ISSUE_TIME
     *
     * @mbggenerated
     */
    private Date issueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.FEEDBACK
     *
     * @mbggenerated
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    private String alipayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.ALIPAY_NAME
     *
     * @mbggenerated
     */
    private String alipayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttx_driver_profile.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.ID
     *
     * @return the value of ttx_driver_profile.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.ID
     *
     * @param id the value for ttx_driver_profile.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.USER_ID
     *
     * @return the value of ttx_driver_profile.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.USER_ID
     *
     * @param userId the value for ttx_driver_profile.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.REAL_NAME
     *
     * @return the value of ttx_driver_profile.REAL_NAME
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.REAL_NAME
     *
     * @param realName the value for ttx_driver_profile.REAL_NAME
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.PHOTO
     *
     * @return the value of ttx_driver_profile.PHOTO
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.PHOTO
     *
     * @param photo the value for ttx_driver_profile.PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.ISSUE_TIME
     *
     * @return the value of ttx_driver_profile.ISSUE_TIME
     *
     * @mbggenerated
     */
    public Date getIssueTime() {
        return issueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.ISSUE_TIME
     *
     * @param issueTime the value for ttx_driver_profile.ISSUE_TIME
     *
     * @mbggenerated
     */
    public void setIssueTime(Date issueTime) {
        this.issueTime = issueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.FEEDBACK
     *
     * @return the value of ttx_driver_profile.FEEDBACK
     *
     * @mbggenerated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.FEEDBACK
     *
     * @param feedback the value for ttx_driver_profile.FEEDBACK
     *
     * @mbggenerated
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.ALIPAY_ACCOUNT
     *
     * @return the value of ttx_driver_profile.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.ALIPAY_ACCOUNT
     *
     * @param alipayAccount the value for ttx_driver_profile.ALIPAY_ACCOUNT
     *
     * @mbggenerated
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.ALIPAY_NAME
     *
     * @return the value of ttx_driver_profile.ALIPAY_NAME
     *
     * @mbggenerated
     */
    public String getAlipayName() {
        return alipayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.ALIPAY_NAME
     *
     * @param alipayName the value for ttx_driver_profile.ALIPAY_NAME
     *
     * @mbggenerated
     */
    public void setAlipayName(String alipayName) {
        this.alipayName = alipayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.STATUS
     *
     * @return the value of ttx_driver_profile.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.STATUS
     *
     * @param status the value for ttx_driver_profile.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.CREATE_TIME
     *
     * @return the value of ttx_driver_profile.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.CREATE_TIME
     *
     * @param createTime the value for ttx_driver_profile.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttx_driver_profile.UPDATE_TIME
     *
     * @return the value of ttx_driver_profile.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttx_driver_profile.UPDATE_TIME
     *
     * @param updateTime the value for ttx_driver_profile.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}