package com.telenav.wzone.database.mapper;

import com.telenav.wzone.database.dto.CarpoolOfferLocation;
import com.telenav.wzone.database.dto.CarpoolOfferLocationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarpoolOfferLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int countByExample(CarpoolOfferLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int deleteByExample(CarpoolOfferLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int insert(CarpoolOfferLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int insertSelective(CarpoolOfferLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    List<CarpoolOfferLocation> selectByExample(CarpoolOfferLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    CarpoolOfferLocation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarpoolOfferLocation record, @Param("example") CarpoolOfferLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarpoolOfferLocation record, @Param("example") CarpoolOfferLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarpoolOfferLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttx_carpool_offer_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarpoolOfferLocation record);

    int insertWithLocation(CarpoolOfferLocation record);

}